package two.group.chatappserver.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "conversation")
public class Conversation {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String conversationId;

    @DynamoDBAttribute
    private String conversationType;

    @DynamoDBAttribute
    private String withName;

    @DynamoDBAttribute
    private String withUid;

    @DynamoDBAttribute
    private String withRole;
}
