package two.group.chatappserver.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "message")
public class Message {

    @DynamoDBAttribute
    private String conversationId;

    @DynamoDBAttribute
    private String category;

    @DynamoDBAttribute
    private DataMessage data;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String receiver;

    @DynamoDBAttribute
    private String receiverType;

    @DynamoDBAttribute
    private String sender;

    @DynamoDBAttribute
    private Long sentAt;

    @DynamoDBAttribute
    private String type;

    @DynamoDBAttribute
    private Long updatedAt;
}
