package two.group.chatappserver.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "user")
public class User {
    @DynamoDBAttribute
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String conversationId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String role;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String uid;

    @DynamoDBAttribute
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String status;

    @DynamoDBAttribute
    private List<Friend> friends;
}
